services:
  financial-forecasting:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FRED_API_KEY=${FRED_API_KEY}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - CONTAINER_NAME=${CONTAINER_NAME:-forecast-predictions}
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHON_ENV=${PYTHON_ENV:-development}
    volumes:
      # Mount local file share simulation for development
      - ./local_fileshare:/mnt/fileshare
      # Optional: Mount logs for debugging (source code stays in container)
      - ./logs:/app/logs

    restart: on-failure
    command: ["--log-level", "INFO"]

# For local development, we use direct directory mounts instead of named volumes
# For production, replace with Azure File Share volume configuration
