version: '3.8'

services:
  financial-forecasting:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FRED_API_KEY=${FRED_API_KEY}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - CONTAINER_NAME=forecast-predictions
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
    volumes:
      # Mount Azure File Share only
      - azure-fileshare:/mnt/fileshare

    restart: on-failure
    command: ["--log-level", "INFO"]

volumes:
  azure-fileshare:
    driver: azure_file
    driver_opts:
      share_name: forecast-pipeline-share
      storage_account_name: forecastsa070369
      storage_account_key: ${AZURE_STORAGE_KEY}
