name: financial-forecasting-pipeline

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 21 * * 5'  # Run every Friday at 09:00 PM UTC

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Build and push container to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/financial-forecasting:latest .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/financial-forecasting:latest
        
    - name: Deploy to Azure Container Instance
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name financial-forecasting-${{ github.run_number }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/financial-forecasting:latest \
            --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --environment-variables FRED_API_KEY=${{ secrets.FRED_API_KEY }} AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} \
            --cpu 2 \
            --memory 8 \
            --restart-policy Never
